baseURL = 'https://mbezjak.github.io'
languageCode = 'en-us'
title = "Well Organized Bits"
theme = "PaperMod"
paginate = 50

[params]
author = "Miro Bezjak"
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true

[params.editPost]
URL = "https://github.com/mbezjak/mbezjak.github.io/blob/main/content"
Text = "Suggest Changes"
appendFilePath = true

[params.analytics.google]
SiteVerificationTag = "62Vyu3hWVePJQe8DUK8iM3Xn2VdjXAAagXEIxsL5To0"

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "email"
name = "Contact"
url = "mailto:well.organized.bits@proton.me"
weight = 15
